name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.rustup
          key: ${{ matrix.target }}-rustup-${{ hashFiles('**/rust-toolchain.toml') }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: |
          rustup target add ${{ matrix.target }}
          cargo install cross
          cross test --target ${{ matrix.target }}
          cross build --release --target ${{ matrix.target }} --bins --artifact-dir target/release/bin -Z unstable-options

      - uses: actions/upload-artifact@v4
        with:
          name: remote-do-${{ matrix.target }}
          path: target/release/bin/*
